var hero=null;var pages=null;var sort=null;var maps=null;var remove=null;var List=new Class({Extends:Loader,Implements:[Options],initialize:function(){this.parent({margin:'200px'});this.list=$$('.guides-list')[0];this.template=$('tpl-guides-list').get('html');},options:{hero:null,page:1,sort:'rating',ver:'iCCup DotA'},request:function(){var self=this;var data='';if(this.options.hero){data='hero_id='+this.options.hero;}
if(this.options.ver){if(data!=''){data+='&';}
data+='ver='+this.options.ver;}
if(this.options.sort){if(data!=''){data+='&';}
data+='sort='+this.options.sort;}
if(this.options.page){if(data!=''){data+='&';}
data+='page='+this.options.page;}
new Request.JSON({url:'/guides/ajax/guides',method:'post',data:data,onRequest:function(){self.loader.on(self.list);},onComplete:function(response){},onSuccess:function(response){self.success(response);}}).send();},success:function(response){this.render(response);remove.bind();},render:function(data){var html=Mustache.to_html(this.template,{rows:data.guides});this.list.set('html',html);}});var Hero=new Class({Extends:List,initialize:function(){this.parent();var self=this;var select=$('select-hero');select.addEvent('change',function(e){self.options.hero=maps.options.hero=pages.options.hero=sort.options.hero=select.get("value");self.request();});},success:function(response){this.parent(response);pages.update(response.pages);}});var Sort=new Class({Extends:List,initialize:function(){this.parent();var self=this;this.buttons=$$('a.sort');this.buttons.addEvent('click',function(e){self.options.sort=maps.options.sort=pages.options.sort=hero.options.sort=this.get('data-sort');self.request();self.buttons.set('class','');$(this).set('class','selected');});},success:function(response){this.parent(response);pages.update(response.pages);}});var MapSort=new Class({Extends:List,initialize:function(){var self=this;this.parent();this.links=$$('.dota-ver a');this.links.addEvent('click',function(){self.options.ver=sort.options.ver=pages.options.ver=hero.options.ver=this.get('data-ver');self.request();});},success:function(response){this.parent(response);pages.update(response.pages);}});var MapControl=new Class({initialize:function(){var self=this;var input=$('inp-ver');if(input&&input.get('value')=='6.83'){$$('.dota-old').addClass('active');$$('.dota-new').removeClass('active');}else{$$('.dota-new').addClass('active');$$('.dota-old').removeClass('active');}
this.links=$$('.dota-ver a');this.links.addEvent('click',function(){self.links.removeClass('active');this.toggleClass('active');if(input){input.set('value',this.get('data-ver'));}});}});var Pages=new Class({Extends:List,initialize:function(){var self=this;this.parent();this.current=1;this.element=$('pages');this.tpl_pages=$('tpl-pages').get('html');$$('.pagination a').addEvent('click',function(e){self.event(this);});},render:function(data){this.parent(data);$('page-'+this.options.page).set('class','current');$('page-'+this.current).set('class','');if(this.options.page==1){$('page-prev').addClass('disabled');}else{$('page-prev').removeClass('disabled');}
if(this.options.page==data.pages){$('page-next').addClass('disabled');}else{$('page-next').removeClass('disabled');}
this.current=this.options.page;},update:function(count){this.options.page=1;this.current=1;var self=this;var data=[];var disabled=(count==1)?'disabled':'';for(var i=2;i<=count;i++){data.push(i);}
var html=Mustache.to_html(this.tpl_pages,{rows:data,next_disabled:disabled});this.element.empty();this.element.set('html',html);$$('.pagination a').addEvent('click',function(e){self.event(this);});},event:function(element){var page=element.get('data-num');var parent=element.getParent('li');if(parent.hasClass('disabled')){return;}
if(page=='next'){page=parseInt(this.current)+1;}
if(page=='prev'){page=parseInt(this.current)-1;}
this.options.page=page;this.request();}});var Skills=new Class({initialize:function(){var self=this;this.skills=$('skills');this.select=$('hero');this.select.addEvent('change',function(){if(this.value!='none'){self.request(this.value);}else{self.skills.addClass('inactive');}});},request:function(hero_id){var self=this;new Request.JSON({url:'/guides/ajax/skills',method:'post',link:'chain',data:'hero_id='+hero_id,onRequest:function(){},onComplete:function(response){},onSuccess:function(response){self.success(response);}}).send();},success:function(response){if(!response.status)return;this.update(response);this.skills.removeClass('inactive');},update:function(data){for(var i=0;i<data.skills.length;i++){var num=i+1;var title='skill-title'+num;var image='skill-image'+num;$(title).set('text',data.skills[i].name);$(image).set('src',data.skills[i].icon);}}});var Items=new Class({initialize:function(){var self=this;this.MAX_ITEMS_COUNT=10;this.period='start';this.items=$('items-list');this.back=$('black-back');this.template=$('tpl_game_item').get('html');this.selected=false;$$('.add-item').addEvent('click',function(event){self.period=this.get('data-period')
self.show();self.selected=false;});$$('.remove-item').addEvent('click',function(event){var period=this.get('data-period');var list=$('list-'+period);var items=list.getElements('.item');var inputs=list.getElements('input');var count=items.length;var item=items.getLast();var input=inputs.getLast();if(item){item.destroy();input.destroy();}
if(count<=1){this.setStyle('display','none');}});this.back.addEvent('click',function(){self.hide();});$$('#items-list .item').addEvent('click',function(event){if(self.selected){return;}
var button=$('btn-remove-'+self.period);var list=$('list-'+self.period);var items=list.getElements('.item');var count=items.length;var data={id:this.get('data-id'),src:this.getElement('img').src,title:this.get('title'),period:self.period};if(count>=self.MAX_ITEMS_COUNT){self.hide();return;}
var html=Mustache.to_html(self.template,data);button.setStyle('display','block');list.set('html',list.get('html')+html);self.hide();self.selected=true;});},show:function(){this.back.fade(0.7);this.items.fade('in');},hide:function(){this.back.fade('out');this.items.fade('out');}});var Vote=new Class({initialize:function(){var self=this;$$('.guide-rate').addEvent('click',function(){var id=this.get('data-id');var direction=this.get('data-rate');self.request(id,direction);});},request:function(id,direction){var self=this;new Request.JSON({url:'/guides/ajax/'+direction,method:'post',link:'chain',data:'gid='+id,onRequest:function(){},onComplete:function(response){},onSuccess:function(response){self.success(response);}}).send();},success:function(response){if(response.status){$('rating').set('html',response.rating);}}});var Submit=new Class({initialize:function(){this.button=$('btn-submit');if(this.button){this.button.addEvent('click',function(){var title=$('title');if(!title.get('value').trim()){title.set('class','form-control required attention');title.focus();title.getParent('div').set('html',title.getParent('div').get('html')+'<span class="error">'+ERROR_EMPTY_TITLE+'</span>')
return false;}});}}});var Remove=new Class({Extends:Loader,initialize:function(){this.parent();this.bind();},bind:function(){var self=this;var buttons=$$('.g-del');if(buttons){$$('.g-del').addEvent('click',function(){var id=this.get('data-id');var parent=this.getParent('li');new Request.JSON({url:'/guides/ajax/remove',method:'post',data:'id='+id,onRequest:function(){self.loader.on(parent);},onComplete:function(response){},onSuccess:function(response){parent.remove();}}).send();});}}});var Levels=new Class({initialize:function(){var self=this;var levels=$$('.s-list input');this.stack=[];levels.addEvent('click',function(){self.stack[this.get('name').toString()]=this.get('value');if(!self.check(self.stack)){this.set('checked','');}});},check:function(list){this.skill_1=0;this.skill_2=0;this.skill_3=0;this.skill_4=0;var prev='';for(var i=1;i<=25;i++){var name_list='level'+i;var name_skill=list[name_list]!=undefined?'skill_'+list[name_list]:false;if(prev&&prev==name_skill){if(name_skill=='skill_4'){if(this[name_skill]==3){return false;}}else{if(this[name_skill]==4){return false;}}}else{this[name_skill]=0;}
this[name_skill]++;prev=name_skill?name_skill:false;}
return true;}});var Tabs=new Class({Implements:[Options,Events],options:{startIndex:0,tabClass:'',tabFilter:'',typeHide:'',activeClass:'active',heroesTable:'.heroes-list'},initialize:function(options){this.setOptions(options);this.heroes=$$(this.options.heroesTable)[0].getElements('a.hero');this.tabs=$$(this.options.tabClass);this.tabsCount=this.tabs.length;this.tabs.each(function(tab,i){this.setupTabs(tab,i);},this);},setupTabs:function(tab,i){tab.addEvent('click',function(e){e.stop();this.currentIndex=i;this.role=tab.getProperty('rel');this.heroes.each(function(el,i){el.removeClass(this.options.typeHide);}.bind(this));this.heroes.each(function(el,i){if(el.get(this.options.tabFilter).indexOf(this.role)<0){el.addClass(this.options.typeHide);}}.bind(this));if(this.activeTab){if(this.activeTab==this.tabs[this.currentIndex]){this.activeTab.removeClass(this.options.activeClass);this.activeTab='';this.heroes.each(function(el,i){if(el.get(this.options.tabFilter).indexOf(this.role)<0){el.removeClass(this.options.typeHide);}}.bind(this));}else{this.activeTab.removeClass(this.options.activeClass);this.activeTab=tab;this.activeTab.addClass(this.options.activeClass);}}else{this.activeTab=tab;this.activeTab.addClass(this.options.activeClass);}}.bind(this));}});var Search=new Class({Implements:[Options,Events],options:{inputName:'#hero-name',activeClass:'active',heroesTable:'.heroes-list'},initialize:function(options){this.setOptions(options);this.input=$$(this.options.inputName);this.heroes=$$(this.options.heroesTable)[0].getElements('a.hero');this.heroesList=[];this.input.addEvent('keyup',function(event){this.key=this.input.get('value');this.heroes.each(function(el,i){var str=String(el.getChildren('span').get('text')).toLowerCase();var result=str.match(this.key);if(result==null){el.addClass('role-hide');}else{el.removeClass('role-hide');el.removeClass('attack-hide');}}.bind(this))}.bind(this))}});window.addEvent('domready',function(){if($('select-hero')){hero=new Hero();}
if($('guide-sort')){sort=new Sort();}
if($('pages')){pages=new Pages();maps=new MapSort();remove=new Remove();}
if($('skills')){new Skills();new Levels();}
if($('add-items')){new Items();}
if($$('.guide-rate')){new Vote();}
if($$('.dota-ver a')){new MapControl();}
new Submit();});